### ISSUE TITLE
copy element on drag

### ISSUE THREAD

**Issue by luisrudge** [a5hik/ng-sortable#122] opened 2015-02-28 02:43 UTC
It's not enough to copy styling. We need to copy the entire element, because it can be more complex than a simple `<li>`.

![ngsortable](https://cloud.githubusercontent.com/assets/941075/6424498/46abbe16-beda-11e4-9304-db9fcdcef3d8.gif)

**Comment by twmulloy** [comment] 2015-03-02 20:38
+1

**Comment by luisrudge** [comment] 2015-03-02 23:02
what's containment and how do I know what is the right one?

**Comment by twmulloy** [comment] 2015-03-03 19:47
Here is the example from the `README.md`, it's a selector for the drag item bounds (parent container). 

```
$scope.dragControlListeners = {
    accept: function (sourceItemHandleScope, destSortableScope) {return boolean}//override to determine drag is allowed or not. default is true.
    itemMoved: function (event) {//Do what you want},
    orderChanged: function(event) {//Do what you want},
    containment: '#board'//optional param.
};

```

When I didn't provide a `containment` param, my list item on drag would disappear and only the placeholder would be visible in the list (as you have shown above). After inspecting the `<body/>` for the `.as-sortable-drag` element that `ng-sortable` creates (that acts as the cloned `<li/>`) I realized it was being appended to the `<body/>` and the absolute positioning that is updated to lock the element to the cursor were off. In addition to that I have some nested css definitions that were messing up the relative positioning:

```
.parent-container > .list {
    /* css definitions */
}
```

When `ng-sortable` goes to clone your list-item it will not wrap it in `.parent-container` so any styles you have declared like above won't get interpreted. So if this is where you have declared positioning styles, etc. you will encountering missing css definitions (this was the 2nd issue I was encountering). I had to define `.list` in a less strict way.

**Comment by luisrudge** [comment] 2015-03-04 03:25
Hey, thanks! Now the styling is ok, but the positioning is messed up. I tried containerPositioning but that didn't fixed it too.

`containerPositioning: 'absolute'`
![ngsortable](https://cloud.githubusercontent.com/assets/941075/6477674/e91bd956-c204-11e4-8b60-d8026b5839d6.gif)


`containerPositioning: 'relative'`
![ngsortable-relative](https://cloud.githubusercontent.com/assets/941075/6477677/ef309d36-c204-11e4-9334-576e90319695.gif)

**Comment by twmulloy** [comment] 2015-03-05 20:27
I had the same problem as I was getting closer to the solution, for me it was off to the right about `90px` so I searched for any elements with a width of `90px` to try and figure out where that offset was coming from and for me it was caused by an adjacent menu list. 

I cannot recall the exact fix but I was able to eventually get it perfect without any css hacks (originally I was using a `margin-left: -90px` hack to offset things back to `0`). I believe it was a matter of isolating the `containment` option very tightly to not include adjacent lists (such as my menu).

Inspect the dom for your `.as-sortable-drag` element during drag and see what `style="left:x, top:y"` you're ending up with and try to make sense of that. I think you might have an element that is confusing the `left` and `top` placement of your drag element.

**Comment by luisrudge** [comment] 2015-03-05 22:09
How did you analyze stuff while dragging anything?

**Comment by twmulloy** [comment] 2015-03-10 06:36
right-click on the element while dragging it to bring up the browser context menu then move your cursor out of the browser to your inspector. it'll preserve the mid-drag element and allow you to inspect (chrome).

**Comment by a5hik** [comment] 2015-03-10 07:13
Hi I see the cursor and the element you drag are no way associated in your sample.

Just check out some of the samples available. and look for the CSS.

**Comment by luisrudge** [comment] 2015-03-13 04:35
Ok guys, I give up. I don't know what's happening, but it doesn't work in my case.

This is without setting `containment`:

![dag-1](https://cloud.githubusercontent.com/assets/941075/6633069/01f81868-c921-11e4-967d-50eb9c66d061.gif)

This is setting `containment:'#q-list'` (q-list is the <ul>):

![dag-2](https://cloud.githubusercontent.com/assets/941075/6633068/01f6ccc4-c921-11e4-8e0c-27928752263a.gif)

I used this just to track the placeholder:
```css
.as-sortable-placeholder {
  border: 1px solid #dcdcdc;
}
```

I don't know why, but I couldn't make this work

**Comment by a5hik** [comment] 2015-11-08 09:18
the clone option is available now and closing this.

**Closed by a5hik** 2015-11-08 09:18 UTC

**Comment by stevehanson** [comment] 2016-03-23 15:48
I still haven't found a fix, but what I noticed is that the item is positioned absolutely while it's being dragged. It looks like the `left` and `top` values are being set to the distance from the top and the left of the page. The problem is that if you have any ancestor elements with `position: relative` or `position: absolute`, then the item will be positioned relative to these, not to the page. 

It's also not clear to me how the clone option is a fix for this issue.
