### ISSUE TITLE
Placeholder position problem

### ISSUE THREAD

**Issue by jonkri** [a5hik/ng-sortable#105] opened 2015-01-23 15:03 UTC
Hi!

Thanks for a nice library!

I have encountered what could be bug in ng-sortable.

First of all, in the Kanban example, let's assume that I want to move "Explore new IDE for Development" card so that it becomes the first list item in the "Not started" column. When I try to do this, ng-sortable does not position the placeholder first, as you can see in this picture:

![ng-sortable-0](https://cloud.githubusercontent.com/assets/777056/5876466/a4888dcc-a317-11e4-8d8a-52a466fe0311.png)

If I continue to drag the placeholder down, and then up again, the placeholder is properly positioned at the top. This seems a bit unexpected, but that's not the issue that I wanted to report (I'm thinking it might be a clue on how to solve the issue, though).

My main problem is about dragging things (like cards) from one <strong>row</strong> to another.

In order to reproduce this, please apply the following CSS to your Kanban example:

    .column, .col-cs-3, .col-sm-3 { float: none; }
    .column { overflow: auto; margin-bottom: 15px; width: 800px; }
    .card { float: left; height: 100px; width: 200px; }
    .as-sortable-placeholder { float: left; }

Now, when I try to drag a card from one row to another, I can't seem to make the placeholder be positioned first. However, this does not happen when I move cards within the same row.

![ng-sortable-1](https://cloud.githubusercontent.com/assets/777056/5876558/61ff4ca6-a318-11e4-8628-869a8fb6bd8e.png)

I'm using Firefox (Iceweasel) 31.3.

Thanks for whatever you can do!

**Comment by MrMDavidson** [comment] 2015-02-12 06:20
I came across the same problem here. It seems like the issue was caused by the commit 7aa7e04feb51d63567b95555932cf1af8933e6bf. If you look at line 703 of ng-sortable.js it's checking the source and destination scope ids. If they're the same (ie. "dragging within the same list") then it does correct horizontal sorting. If you've dragged from a different sortable, though, it always handles it as a vertical sort, even though itemPosition.dirAx is non-zero.

I'm not 100% sure of the bug this is meant to fix. In a fork of the library I've removed the id check and it works correctly for horizontal sorts when originating from a different sortable. Eg.

```javascript
                if (targetScope.sortableScope.accept(scope, targetScope.sortableScope, targetScope)) {
                  if (itemPosition.dirAx) {
                    itemPosition.distAxX = 0;
                    if (itemPosition.distX < 0) {//move left
                      insertBefore(targetElement, targetScope);
                    } else if (itemPosition.distX > 0) {//move right
                      insertAfter(targetElement, targetScope);
                    }
                  } else { //move vertical
```

**Comment by jonkri** [comment] 2015-02-13 12:39
Thanks for your comment, @MrMDavidson!

@a5hik: Is this perhaps something that we can fix in the official version of ng-sortable?

**Comment by a5hik** [comment] 2015-05-14 08:25
the version 1.2.1 having a fix for this problem.

**Closed by a5hik** 2015-05-14 08:25 UTC
